-- POSSIAMO CONCATENARE
SELECT TIPO_AEREO, NUM_PASS, QTA_MERCI
FROM dbetl.AEREO
WHERE num_pass=120
AND qta_merci=300
OR num_pass=115;

--- possiamo utilizzare le parentesi per isolare le condizioni:

SELECT TIPO_AEREO, NUM_PASS, QTA_MERCI
FROM dbetl.AEREO
WHERE (num_pass=120 AND qta_merci=300)
OR num_pass=115;

---- CONDIZIONI NEL WHERE CON IN: 
-- ( VA A SOSTIUIRE TANTO OR CONCATENATI)
SELECT TIPO_AEREO, NUM_PASS, QTA_MERCI
FROM dbetl.AEREO
WHERE num_pass IN (120,130,115);

--POSSIAMO UTILIZZARE ANCHE LA NEGAZIONE :
SELECT TIPO_AEREO, NUM_PASS, QTA_MERCI
FROM dbetl.AEREO
WHERE num_pass NOT IN (120,130,115); -- nb: NON SI PUò UTILIZZARE <>  O !=

-- Where con utilizzo di between ( utilizzato per cercare in un range di valori, possono
-- essere sia stringhe chhe numeri o date)

SELECT TIPO_AEREO, NUM_PASS, QTA_MERCI
FROM DBETL.AEREO
WHERE num_pass BETWEEN 120 AND 200
ORDER BY NUM_PASS; -- CON asc (DEFAULT) ORDINA IN MANIERA CRESCENTE / CON desc , DECRESCENTE 
-- ORDER BY DEVE ESSERE SEMPRE L'ULTIMO COMANDO.

-- WHERE CON BETWEEN E NEGAZIONE :
SELECT TIPO_AEREO, NUM_PASS, QTA_MERCI
FROM DBETL.AEREO
WHERE num_pass NOT BETWEEN 120 AND 200 -- nb: NON SI PUò UTILIZZARE <>  O !=
ORDER BY NUM_PASS;

-- IL COMANDO IS NULL VIENE UTILIZZATO PER REPERIRE RIGHE CON VALORI DI TIPO NULL:
SELECT TIPO_AEREO, NUM_PASS, QTA_MERCI
FROM DBETL.AEREO
WHERE num_pass IS NULL;

-- WHERE CON UTILIZZO DI LIKE ( SERVE PER CERCARE CARATTERI)
-- voglio gli aerei che cominciano con la lettera A:

SELECT TIPO_AEREO, NUM_PASS, QTA_MERCI
FROM DBETL.AEREO
WHERE tipo_aereo LIKE 'A%'; -- è importante rispettare la formattazione dei caratteri nella tabella

--voglio gli aerei che hanno nel nome la Z come secondo carattere:
SELECT TIPO_AEREO, NUM_PASS, QTA_MERCI
FROM DBETL.AEREO
WHERE tipo_aereo LIKE '_Z%';

-- SE  VOGLIO CERCARE UN CARATTERE MA NON NE CONOSCO LA POSIZIONE:

SELECT TIPO_AEREO, NUM_PASS, QTA_MERCI
FROM DBETL.AEREO
WHERE tipo_aereo LIKE '%9%';

--POSSO CERCARE PIù DI UN CARATTERE, MA LA RICERCA AVVIENE DA SX VERSO DX:

SELECT TIPO_AEREO, NUM_PASS, QTA_MERCI
FROM DBETL.AEREO
WHERE tipo_aereo LIKE '%9%R%'; -- IN QUESTO CASO UN RISULTATO VALIDO POTREBBE ESSERE : AZ90R5 MA NON AZR095

-- ANCHE IL PREDICATO LIKE AMMETTE LA NEGAZIONE :

SELECT TIPO_AEREO, NUM_PASS, QTA_MERCI
FROM DBETL.AEREO
WHERE tipo_aereo NOT LIKE '%9%';


                        ------- LE FUNZIONI DI AGGREGAZIONE----------  
--- SOMMA :
SELECT SUM(NUM_PASS)
FROM DBETL.aereo
WHERE tipo_aereo LIKE 'A%';

---- NUMERO MAGGIORE: 
SELECT MAX(NUM_PASS)
FROM dbetl.AEREO
WHERE TIPO_AEREO LIKE '_Z%';

---- NUMERO MINORE:
SELECT MIN(NUM_PASS)
FROM dbetl.AEREO
WHERE TIPO_AEREO LIKE '_Z%';

---CONTEGGIO DELLE RIGHE:
SELECT COUNT(NUM_PASS) -- PER CONTARE TUTTE LE RIGHE DELL'INTERA TABELLA SI PUò UTILIZZARE (*)
FROM dbetl.AEREO
WHERE TIPO_AEREO LIKE '_Z%';

--- RINOMINA DI COLONNA A RUNTIME:
SELECT COUNT(NUM_PASS) AS CONTEGGIO
FROM dbetl.AEREO
WHERE TIPO_AEREO LIKE '_Z%';

--- voglio cambiare a runtime il tipo di aereo con una nuova stringa:

SELECT NUM_PASS, QTA_MERCI, 'Jet' AS TIPO_AEREO -- NELL'ISTAZIONE DI COLONNA NON POSSONO ESSERCI SPAZI!!
FROM DBETL.AEREO
WHERE tipo_aereo LIKE '_Z%';

