-- possiamo utilizzare gli operatori matematici:

SELECT NOME, COGNOME, STIPENDIO, BONUS, COMMISSIONI, 
(STIPENDIO + BONUS + COMMISSIONI) AS TOT_STIPENDIO
FROM DBETL.DIPENDENTI;

-- POSSIAMO FARE IL CAST DEI VALORI NELLE COLONNE:
--ESEMPIO: TRASFORMO LIVELLO ISTRUZIONE IN STRINGA:

-- ESISTONO ANCHE LE FUNZ: TO_NUMBER(), TO_DATE()
SELECT LIVELLO_ISTRUZIONE AS NUM_FORMAT
      ,TO_CHAR(LIVELLO_ISTRUZIONE) AS CHAR_FORMAT
  FROM DBETL.DIPENDENTI;
  
--UNION--

SELECT ' dipendente: ' as colonna, NOME as nome,' cognome' as cogn, COGNOME as cognome_dip, id_anag as num
FROM DBETL.anagrafe_DIPENDENTI
where sesso='D' 
UNION
SELECT ' Aeroporto:' as colonna, CITTA as citt,' nazione' as cogn, NAZIONE as naz, NUM_PISTE as piste
FROM DBETL.aeroporti
ORDER BY COGN; -- ALIAS